server:
  port: 8761                    # 指定该Eureka实例的端口

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: 127.0.0.1 #101.132.143.246  # 指定该Eureka实例的主机名
    prefer-ip-address: true   # 使用IP访问
    ip-address: 127.0.0.1 #101.132.143.246 #外网地址
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false  # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 5000  # 清理间隔（单位毫秒，默认是60*1000）

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756